### ISSUE TITLE
文件太多了

### ISSUE THREAD

**Issue by feilongproject** [dd-center/bili-av#1]
如题，所有文件加起来没有多少用到的，能不能出一个单文件版或者仅html、css、js版本的

**Comment by ilharp** [comment]
核心算法在这里哦~

https://github.com/dd-center/bili-av/blob/master/utils/converter.js

静态站的打包在这里（其实只要跑一下 `npm run website:generate` 就可以了

[dist.zip](https://github.com/dd-center/bili-av/files/4375110/dist.zip)

解压后直接 `npx serve` 即可

过几个小时将会推出 Electron 版本

之后我会更新 `README.md`，用来指路

**Comment by ilharp** [comment]
该问题因为长时间的闲置而关闭。

若有任何其他问题，请在下方讨论。
